In [1]:
import pandas as pd
import numpy as np

In [2]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [8]:
date['date']=pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
#Extract Year
date['date_year']=date['date'].dt.year

#here, dt is an accessor object that allows us to access the datetime properties of the 'date' column. We can use dt.year to extract the year from the datetime object and create a new column 'date_year' in the dataframe.
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [10]:
date['date_month_no']=date['date'].dt.month
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [11]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [13]:
date['date_dayOfTheWeek']=date['date'].dt.dayofweek
date['date_dayOfTheWeek_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayOfTheWeek,date_dayOfTheWeek_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [14]:
#is Weekend?

date['date_is_weekend']=np.where(date['date_dayOfTheWeek_name'].isin(['Saturday','Sunday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayOfTheWeek,date_dayOfTheWeek_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [17]:
date['date_week']=date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayOfTheWeek,date_dayOfTheWeek_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [19]:
date['quarter'] = date['date'].dt.quarter
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayOfTheWeek,date_dayOfTheWeek_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

In [20]:
#elapsed time bw dates
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 9, 7, 23, 32, 11, 564171)

In [21]:
today - date['date']

0     2463 days 23:32:11.564171
1     2945 days 23:32:11.564171
2     2876 days 23:32:11.564171
3     2578 days 23:32:11.564171
4     2801 days 23:32:11.564171
                 ...
995   2891 days 23:32:11.564171
996   2832 days 23:32:11.564171
997   2680 days 23:32:11.564171
998   2745 days 23:32:11.564171
999   2519 days 23:32:11.564171
Name: date, Length: 1000, dtype: timedelta64[ns]

In [23]:
(today - date['date']).dt.days

0      2463
1      2945
2      2876
3      2578
4      2801
       ...
995    2891
996    2832
997    2680
998    2745
999    2519
Name: date, Length: 1000, dtype: int64

In [27]:
# Months passed
months = (
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
)

print(months)

0      81
1      97
2      95
3      85
4      92
       ..
995    95
996    93
997    88
998    90
999    83
Name: date, Length: 1000, dtype: int32

In [28]:
#working with time and messages dataset
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [29]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [31]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [32]:
today - time['date']

0     4649 days 22:42:11.564171
1     4513 days 23:52:11.564171
2     4999 days 23:11:11.564171
3     4301 days 23:01:11.564171
4     4699 days 00:21:11.564171
                 ...
995   5288 days 22:42:11.564171
996   4610 days 00:18:11.564171
997   5074 days 23:55:11.564171
998   5190 days 23:58:11.564171
999   4463 days 00:07:11.564171
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.017553e+08
1      3.900091e+08
2      4.319971e+08
3      3.716893e+08
4      4.059949e+08
           ...
995    4.569649e+08
996    3.983051e+08
997    4.384797e+08
998    4.485023e+08
999    3.856036e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.695922e+06
1      6.500152e+06
2      7.199951e+06
3      6.194821e+06
4      6.766581e+06
           ...
995    7.616082e+06
996    6.638418e+06
997    7.307995e+06
998    7.475038e+06
999    6.426727e+06
Name: date, Length: 1000, dtype: float64

In [35]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      111598.703212
1      108335.869879
2      119999.186546
3      103247.019879
4      112776.353212
           ...
995    126934.703212
996    110640.303212
997    121799.919879
998    124583.969879
999    107112.119879
Name: date, Length: 1000, dtype: float64